### ISSUE TITLE
Can't install properly

### ISSUE THREAD

**Issue by AmirFB** [Maratyszcza/pthreadpool#19]
I am new to make/cmake and can't install this library properly. I used these commands in order:

> cmake -S * -B build
> cd build
> make
> sudo make install

But, when I try to compile addition.c file, get this error:

/usr/bin/ld: /tmp/cc3SOpOd.o: in function `main':
addition.c:(.text+0xe3): undefined reference to `pthreadpool_create'
/usr/bin/ld: addition.c:(.text+0x122): undefined reference to `pthreadpool_get_threads_count'
/usr/bin/ld: addition.c:(.text+0x18a): undefined reference to `pthreadpool_parallelize_1d'
/usr/bin/ld: addition.c:(.text+0x199): undefined reference to `pthreadpool_destroy'
collect2: error: ld returned 1 exit status

**Comment by ur4t** [comment]
Use `cc addition.c -lpthreadpool -lpthread` to compile the example.
