### ISSUE TITLE
Set cpu affinity through pthreadpool_create()

### ISSUE THREAD

**Issue by lk-chen** [Maratyszcza/pthreadpool#44]
Currently pthreadpool_create() only take a size_t indicating number of threads. Shall we add capability to specify cpu affinity?

**Comment by Maratyszcza** [comment]
Affinity is not portable, e.g. macOS doesn't support it. The best we can do is provide a hint of the current CPU core, similarly to `pthreadpool_parallelize_*_with_thread` functions.
