### ISSUE TITLE
pthreadpool_deallocate and pthreadpool_allocate are not defined.

### ISSUE THREAD

**Issue by iand111** [Maratyszcza/pthreadpool#8]
I am having trouble building pthreadpool (the end goal is to build NNPACK and NNPACK-darknet). First I run confu setup and python configure.py before failing to build using ninja. I see these functions are defined in the threadpool-object.h file, but cannot locate its implementation. Could I be missing a dependency somewhere? Thank you in advance.

**Comment by Maratyszcza** [comment]
Please use CMake to build pthreadpool. Confu build is deprecated.
