### ISSUE TITLE
Help pytorch migrate to the "new" API

### ISSUE THREAD

**Issue by mattip** [Maratyszcza/pthreadpool#9]
`pthreadpool_function_1d_tiled_t` and friends are deprecated. These are producing many warnings when building pytorch: they are used in [`quantized/cpu/cnnpack`](https://github.com/pytorch/pytorch/blob/v1.6.0-rc3/aten/src/ATen/native/quantized/cpu/qnnpack/src/). It would be nice if someone well versed in pthreadpool could provide some guidance or even a PR to update them.

**Comment by Maratyszcza** [comment]
This is out of scope of this project. You should open this issue in PyTorch.
